openapi: 3.0.0
info:
  title: Device API
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /devices/psu1/stats:
    get:
      summary: Get PSU1 stats info
      responses:
        '200':
          description: PSU1 stats response
          content:
            application/json:
              schema:
                type: object
                properties:
                  voltage:
                    type: number
                  current:
                    type: number

  /devices/psu1/command:
    post:
      summary: Send command to PSU1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
              required:
                - command
      responses:
        '200':
          description: Command accepted
